version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 3.1
        commands:
            - dotnet tool install -g trx2junit
    build:
        commands:
            - dotnet build -c Release ./CodeBuildDotnetTestReportExample/CodeBuildDotnetTestReportExample.csproj
            - dotnet test -c Release ./CodeBuildDotnetTestReportExample.Tests/CodeBuildDotnetTestReportExample.Tests.csproj --logger trx --results-directory ./testresults
    post_build:
        commands:
            - ~/.dotnet/tools/trx2junit ./testresults/*
reports:
    DotnetTestExamples:
        files:
            - '**/*'
        base-directory: './testresults'          